/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_games_input_OSXHIDDeviceIterator */

#ifndef _Included_net_java_games_input_OSXHIDDeviceIterator
#define _Included_net_java_games_input_OSXHIDDeviceIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_games_input_OSXHIDDeviceIterator
 * Method:    nCreateIterator
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_games_input_OSXHIDDeviceIterator_nCreateIterator
  (JNIEnv *, jclass);

/*
 * Class:     net_java_games_input_OSXHIDDeviceIterator
 * Method:    nReleaseIterator
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_OSXHIDDeviceIterator_nReleaseIterator
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_games_input_OSXHIDDeviceIterator
 * Method:    nNext
 * Signature: (J)Lnet/java/games/input/OSXHIDDevice;
 */
JNIEXPORT jobject JNICALL Java_net_java_games_input_OSXHIDDeviceIterator_nNext
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
