/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_games_input_OSXHIDDevice */

#ifndef _Included_net_java_games_input_OSXHIDDevice
#define _Included_net_java_games_input_OSXHIDDevice
#ifdef __cplusplus
extern "C" {
#endif
#undef net_java_games_input_OSXHIDDevice_AXIS_DEFAULT_MIN_VALUE
#define net_java_games_input_OSXHIDDevice_AXIS_DEFAULT_MIN_VALUE 0L
#undef net_java_games_input_OSXHIDDevice_AXIS_DEFAULT_MAX_VALUE
#define net_java_games_input_OSXHIDDevice_AXIS_DEFAULT_MAX_VALUE 65536L
/*
 * Class:     net_java_games_input_OSXHIDDevice
 * Method:    nGetDeviceProperties
 * Signature: (J)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_net_java_games_input_OSXHIDDevice_nGetDeviceProperties
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_games_input_OSXHIDDevice
 * Method:    nReleaseDevice
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_OSXHIDDevice_nReleaseDevice
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     net_java_games_input_OSXHIDDevice
 * Method:    nGetElementValue
 * Signature: (JJLnet/java/games/input/OSXEvent;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_OSXHIDDevice_nGetElementValue
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     net_java_games_input_OSXHIDDevice
 * Method:    nCreateQueue
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_net_java_games_input_OSXHIDDevice_nCreateQueue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_games_input_OSXHIDDevice
 * Method:    nOpen
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_OSXHIDDevice_nOpen
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_games_input_OSXHIDDevice
 * Method:    nClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_OSXHIDDevice_nClose
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
