/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_games_input_OSXHIDQueue */

#ifndef _Included_net_java_games_input_OSXHIDQueue
#define _Included_net_java_games_input_OSXHIDQueue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_games_input_OSXHIDQueue
 * Method:    nOpen
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_OSXHIDQueue_nOpen
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     net_java_games_input_OSXHIDQueue
 * Method:    nClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_OSXHIDQueue_nClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_games_input_OSXHIDQueue
 * Method:    nStart
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_OSXHIDQueue_nStart
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_games_input_OSXHIDQueue
 * Method:    nStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_OSXHIDQueue_nStop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_games_input_OSXHIDQueue
 * Method:    nReleaseQueue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_OSXHIDQueue_nReleaseQueue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_games_input_OSXHIDQueue
 * Method:    nAddElement
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_OSXHIDQueue_nAddElement
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     net_java_games_input_OSXHIDQueue
 * Method:    nRemoveElement
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_OSXHIDQueue_nRemoveElement
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     net_java_games_input_OSXHIDQueue
 * Method:    nGetNextEvent
 * Signature: (JLnet/java/games/input/OSXEvent;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_java_games_input_OSXHIDQueue_nGetNextEvent
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
