/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_games_input_WinTabContext */

#ifndef _Included_net_java_games_input_WinTabContext
#define _Included_net_java_games_input_WinTabContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_games_input_WinTabContext
 * Method:    nGetNumberOfSupportedDevices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_WinTabContext_nGetNumberOfSupportedDevices
  (JNIEnv *, jclass);

/*
 * Class:     net_java_games_input_WinTabContext
 * Method:    nOpen
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_net_java_games_input_WinTabContext_nOpen
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_games_input_WinTabContext
 * Method:    nClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_WinTabContext_nClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_games_input_WinTabContext
 * Method:    nGetPackets
 * Signature: (J)[Lnet/java/games/input/WinTabPacket;
 */
JNIEXPORT jobjectArray JNICALL Java_net_java_games_input_WinTabContext_nGetPackets
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
