/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_games_input_WinTabDevice */

#ifndef _Included_net_java_games_input_WinTabDevice
#define _Included_net_java_games_input_WinTabDevice
#ifdef __cplusplus
extern "C" {
#endif
#undef net_java_games_input_WinTabDevice_EVENT_QUEUE_DEPTH
#define net_java_games_input_WinTabDevice_EVENT_QUEUE_DEPTH 32L
/*
 * Class:     net_java_games_input_WinTabDevice
 * Method:    nGetName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_games_input_WinTabDevice_nGetName
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_java_games_input_WinTabDevice
 * Method:    nGetAxisDetails
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_net_java_games_input_WinTabDevice_nGetAxisDetails
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_java_games_input_WinTabDevice
 * Method:    nGetCursorNames
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_net_java_games_input_WinTabDevice_nGetCursorNames
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_java_games_input_WinTabDevice
 * Method:    nGetMaxButtonCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_WinTabDevice_nGetMaxButtonCount
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
