/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_games_input_IDirectInputEffect */

#ifndef _Included_net_java_games_input_IDirectInputEffect
#define _Included_net_java_games_input_IDirectInputEffect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_games_input_IDirectInputEffect
 * Method:    nRelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_IDirectInputEffect_nRelease
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_games_input_IDirectInputEffect
 * Method:    nSetGain
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_IDirectInputEffect_nSetGain
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     net_java_games_input_IDirectInputEffect
 * Method:    nStart
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_IDirectInputEffect_nStart
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     net_java_games_input_IDirectInputEffect
 * Method:    nStop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_IDirectInputEffect_nStop
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
