/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_games_input_LinuxJoystickDevice */

#ifndef _Included_net_java_games_input_LinuxJoystickDevice
#define _Included_net_java_games_input_LinuxJoystickDevice
#ifdef __cplusplus
extern "C" {
#endif
#undef net_java_games_input_LinuxJoystickDevice_JS_EVENT_BUTTON
#define net_java_games_input_LinuxJoystickDevice_JS_EVENT_BUTTON 1L
#undef net_java_games_input_LinuxJoystickDevice_JS_EVENT_AXIS
#define net_java_games_input_LinuxJoystickDevice_JS_EVENT_AXIS 2L
#undef net_java_games_input_LinuxJoystickDevice_JS_EVENT_INIT
#define net_java_games_input_LinuxJoystickDevice_JS_EVENT_INIT 128L
#undef net_java_games_input_LinuxJoystickDevice_AXIS_MAX_VALUE
#define net_java_games_input_LinuxJoystickDevice_AXIS_MAX_VALUE 32767L
/*
 * Class:     net_java_games_input_LinuxJoystickDevice
 * Method:    nOpen
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_net_java_games_input_LinuxJoystickDevice_nOpen
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_java_games_input_LinuxJoystickDevice
 * Method:    nGetNextEvent
 * Signature: (JLnet/java/games/input/LinuxJoystickEvent;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_java_games_input_LinuxJoystickDevice_nGetNextEvent
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     net_java_games_input_LinuxJoystickDevice
 * Method:    nGetNumButtons
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_LinuxJoystickDevice_nGetNumButtons
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_games_input_LinuxJoystickDevice
 * Method:    nGetNumAxes
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_LinuxJoystickDevice_nGetNumAxes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_games_input_LinuxJoystickDevice
 * Method:    nGetAxisMap
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_java_games_input_LinuxJoystickDevice_nGetAxisMap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_games_input_LinuxJoystickDevice
 * Method:    nGetButtonMap
 * Signature: (J)[C
 */
JNIEXPORT jcharArray JNICALL Java_net_java_games_input_LinuxJoystickDevice_nGetButtonMap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_games_input_LinuxJoystickDevice
 * Method:    nGetVersion
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_LinuxJoystickDevice_nGetVersion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_games_input_LinuxJoystickDevice
 * Method:    nGetName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_games_input_LinuxJoystickDevice_nGetName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_games_input_LinuxJoystickDevice
 * Method:    nClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_LinuxJoystickDevice_nClose
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
