/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_games_input_LinuxEventDevice */

#ifndef _Included_net_java_games_input_LinuxEventDevice
#define _Included_net_java_games_input_LinuxEventDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_games_input_LinuxEventDevice
 * Method:    nOpen
 * Signature: (Ljava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_net_java_games_input_LinuxEventDevice_nOpen
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     net_java_games_input_LinuxEventDevice
 * Method:    nUploadRumbleEffect
 * Signature: (JIIIIIIII)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_LinuxEventDevice_nUploadRumbleEffect
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     net_java_games_input_LinuxEventDevice
 * Method:    nUploadConstantEffect
 * Signature: (JIIIIIIIIIII)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_LinuxEventDevice_nUploadConstantEffect
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     net_java_games_input_LinuxEventDevice
 * Method:    nEraseEffect
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_LinuxEventDevice_nEraseEffect
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     net_java_games_input_LinuxEventDevice
 * Method:    nWriteEvent
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_LinuxEventDevice_nWriteEvent
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     net_java_games_input_LinuxEventDevice
 * Method:    nGetInputID
 * Signature: (J)Lnet/java/games/input/LinuxInputID;
 */
JNIEXPORT jobject JNICALL Java_net_java_games_input_LinuxEventDevice_nGetInputID
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_games_input_LinuxEventDevice
 * Method:    nGetNumEffects
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_LinuxEventDevice_nGetNumEffects
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_games_input_LinuxEventDevice
 * Method:    nGetVersion
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_java_games_input_LinuxEventDevice_nGetVersion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_games_input_LinuxEventDevice
 * Method:    nGetNextEvent
 * Signature: (JLnet/java/games/input/LinuxEvent;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_java_games_input_LinuxEventDevice_nGetNextEvent
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     net_java_games_input_LinuxEventDevice
 * Method:    nGetAbsInfo
 * Signature: (JILnet/java/games/input/LinuxAbsInfo;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_LinuxEventDevice_nGetAbsInfo
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     net_java_games_input_LinuxEventDevice
 * Method:    nGetBits
 * Signature: (JI[B)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_LinuxEventDevice_nGetBits
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

/*
 * Class:     net_java_games_input_LinuxEventDevice
 * Method:    nGetDeviceUsageBits
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_LinuxEventDevice_nGetDeviceUsageBits
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     net_java_games_input_LinuxEventDevice
 * Method:    nGetKeyStates
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_LinuxEventDevice_nGetKeyStates
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     net_java_games_input_LinuxEventDevice
 * Method:    nGetName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_games_input_LinuxEventDevice_nGetName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_games_input_LinuxEventDevice
 * Method:    nClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_LinuxEventDevice_nClose
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
