/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_games_input_RawInputEnvironmentPlugin */

#ifndef _Included_net_java_games_input_RawInputEnvironmentPlugin
#define _Included_net_java_games_input_RawInputEnvironmentPlugin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_games_input_RawInputEnvironmentPlugin
 * Method:    enumerateDevices
 * Signature: (Lnet/java/games/input/RawInputEventQueue;Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_RawInputEnvironmentPlugin_enumerateDevices
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     net_java_games_input_RawInputEnvironmentPlugin
 * Method:    nEnumSetupAPIDevices
 * Signature: ([BLjava/util/List;)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_RawInputEnvironmentPlugin_nEnumSetupAPIDevices
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     net_java_games_input_RawInputEnvironmentPlugin
 * Method:    getKeyboardClassGUID
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_java_games_input_RawInputEnvironmentPlugin_getKeyboardClassGUID
  (JNIEnv *, jclass);

/*
 * Class:     net_java_games_input_RawInputEnvironmentPlugin
 * Method:    getMouseClassGUID
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_java_games_input_RawInputEnvironmentPlugin_getMouseClassGUID
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
