/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_games_input_RawInputEventQueue_QueueThread */

#ifndef _Included_net_java_games_input_RawInputEventQueue_QueueThread
#define _Included_net_java_games_input_RawInputEventQueue_QueueThread
#ifdef __cplusplus
extern "C" {
#endif
#undef net_java_games_input_RawInputEventQueue_QueueThread_MIN_PRIORITY
#define net_java_games_input_RawInputEventQueue_QueueThread_MIN_PRIORITY 1L
#undef net_java_games_input_RawInputEventQueue_QueueThread_NORM_PRIORITY
#define net_java_games_input_RawInputEventQueue_QueueThread_NORM_PRIORITY 5L
#undef net_java_games_input_RawInputEventQueue_QueueThread_MAX_PRIORITY
#define net_java_games_input_RawInputEventQueue_QueueThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
