/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_games_input_DummyWindow */

#ifndef _Included_net_java_games_input_DummyWindow
#define _Included_net_java_games_input_DummyWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_games_input_DummyWindow
 * Method:    createWindow
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_games_input_DummyWindow_createWindow
  (JNIEnv *, jclass);

/*
 * Class:     net_java_games_input_DummyWindow
 * Method:    nDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_java_games_input_DummyWindow_nDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
